### ISSUE TITLE
New CRAN release

### ISSUE THREAD

**Issue by markfairbanks** [marianschmidt/msSPChelpR#104]
Hello - I am looking to release a new version of `tidytable` to CRAN that removes all `verb.()` versions of functions. I have my reverse dependency checks failing since you used to use them.

As far as I can tell you already removed all of those functions from your code - would you be able to submit a new version off `msSPChelpR` to CRAN in the next couple weeks so I can get the new version of `tidytable` uploaded? Thanks for the help!

**Comment by marianschmidt** [comment]
Hi @markfairbanks ,
Sure, I can plan another release to CRAN within the next week or two.

**Comment by marianschmidt** [comment]
New version is on CRAN
