### ISSUE TITLE
CRAN rejecting tidytable v0.5.8 due to msSPChelpR

### ISSUE THREAD

**Issue by markfairbanks** [marianschmidt/msSPChelpR#66]
I'm trying to release the latest tidytable, however CRAN is giving me this error:

```
Package: msSPChelpR
Check: re-building of vignette outputs
New result: WARNING
  Error(s) in re-building vignettes:
    ...
  --- re-building ‘introduction.Rmd’ using rmarkdown
  Quitting from lines 237-257 (introduction.Rmd) 
  Error: processing vignette 'introduction.Rmd' failed with diagnostics:
  could not find function "mutate."
  --- failed re-building ‘introduction.Rmd’

  SUMMARY: processing the following file failed:
    ‘introduction.Rmd’
```
Can you update to the latest tidytable using `devtools::install_github("markfairbanks/tidytable")` and see if you can build this vignette?

I think this is occurring because I bumped the vctrs dependency, but I figured that CRAN's checks would include that.

Thanks for the help!

**Comment by marianschmidt** [comment]
It seems like this occurred because I removed `library(tidytable)` from the vignette (I only added it temporarily, because before the `expand().` function was not exported). Could it be that something is different with exporting the `mutate.()` function?

**Comment by markfairbanks** [comment]
I didn't make any changes to `mutate.()` except for a couple internal comments. And yep - I remember the issue with `expand.()`. There's nothing I know of in `mutate.()` that would cause that issue.

Just to make sure I understand - is your vignette failing right now if you run it with the newest version of tidytable? Does it still fail if you add back in `libarary(tidytable)`?

**Comment by marianschmidt** [comment]
It seems to occur in a `mutate_across.()` call. 
I think it is this one:

```
 df <- df%>%
    tidytable::mutate_across.(.cols = where(is.factor), .fns = as.character)

```
giving this error.

```
Fehler in mutate.(.df, age = (structure(function(..., .x = ..1, .y = ..2, : konnte Funktion "mutate." nicht finden
6.
eval_tidy(result_expr, new_data_mask(data_env), caller_env())
5.
mutate_across..data.frame(., .cols = c(age, sex, region, year, t_site), .fns = ~tidytable::replace_na.(., na_explicit))
4.
tidytable::mutate_across.(., .cols = c(age, sex, region, year, t_site), .fns = ~tidytable::replace_na.(., na_explicit))
3.
df %>% tidytable::mutate.(age = as.character(!!age_var), sex = as.character(!!sex_var), region = as.character(!!region_var), year = as.character(!!year_var), t_site = as.character(!!site_var)) %>% tidytable::mutate_across.(.cols = c(age, sex, region, year, t_site), .fns = ~tidytable::replace_na.(., ...
2.
sir_byfutime(., dattype = "seer", ybreak_vars = c("race.1", "t_dco.1"), xbreak_var = "none", futime_breaks = c(0, 1/12, 2/12, 1, 5, 10, Inf), count_var = "count_spc", refrates_df = us_refrates_icd2, calc_total_row = TRUE, calc_total_fu = TRUE, region_var = "registry.1", ...
1.
usdata_wide %>% sir_byfutime(dattype = "seer", ybreak_vars = c("race.1", "t_dco.1"), xbreak_var = "none", futime_breaks = c(0, 1/12, 2/12, 1, 5, 10, Inf), count_var = "count_spc", refrates_df = us_refrates_icd2, calc_total_row = TRUE, calc_total_fu = TRUE, region_var = "registry.1", ...
```

**Comment by markfairbanks** [comment]
Ah yep, that's it! I think I know exactly what the issue is. I did make changes to `mutate_across.()`. Thanks for catching this. I'll let you know when I have it fixed

**Comment by markfairbanks** [comment]
All fixed! But I was already able to reproduce the error and verify it worked. Thanks for the help!
