### ISSUE TITLE
New CRAN Release of `msSPChelpR`

### ISSUE THREAD

**Issue by markfairbanks** [marianschmidt/msSPChelpR#83]
@marianschmidt would you be able to send a new release to CRAN? An issue was found in the CRAN version of `msSPChelpR` since `sir_byfutime()` used `bind_rows.(fill = TRUE)` at that time.

The development version of `msSPChelpR` has already fixed the issue, so a new CRAN release would allow `tidytable` 0.8.0 to be accepted to CRAN.

Thanks for the help!

**Comment by marianschmidt** [comment]
Hi @markfairbanks, I need to do a few checks, but I will try to release as fast as possible.

**Comment by marianschmidt** [comment]
related to #53

**Comment by marianschmidt** [comment]
closed via #87 

Hi @markfairbanks, new release is on CRAN. Hope, you are good to go now.

**Comment by markfairbanks** [comment]
`tidytable` was accepted by CRAN, thanks again @marianschmidt
